name: Hello World workflow

on:
  push:
    branches:
      - feature-branch

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: print Hello World
        run: echo "Hello World" && sleep 10
      - name: print Hello New Era Solutions
        run: echo "Hello New Era Solutions" && sleep 10  
